"""Upgrade embedding dimension from 1024 (Qwen3-0.6B) to 1536 (Qwen3-4B Matryoshka).

Revision ID: 003
Revises: 002
Create Date: 2026-04-17

Why:
  Switching from Qwen/Qwen3-Embedding-0.6B (1024d) to Qwen/Qwen3-Embedding-4B
  with Matryoshka truncation to 1536d. The 4B model has 7x more parameters and
  significantly better semantic understanding for Traditional Chinese legal text.
  1536d is chosen because:
    - 50% more signal than 1024d
    - Stays within pgvector HNSW's 2000-dimension hard limit
    - Matryoshka allows requesting any sub-dimension from the 4B model

  All existing child_chunks rows must be deleted because their embeddings were
  generated by the old model (0.6B/1024d) and live in a different vector space.
  Re-run ingestion after applying this migration.

Steps performed:
  1. Drop the HNSW index (cannot ALTER a vector column with an active index)
  2. Delete all child_chunks rows (old embeddings are invalid)
  3. ALTER COLUMN embedding TYPE vector(1536)
  4. Recreate the HNSW index for 1536d
"""

from alembic import op
import sqlalchemy as sa

revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Drop HNSW index if it exists — required before altering vector column type.
    #    Use IF EXISTS because a previous partial migration may have already dropped it.
    op.execute(
        "DROP INDEX IF EXISTS ix_child_chunks_embedding_hnsw"
    )

    # 2. Delete all existing embeddings — invalid regardless of source dimension.
    op.execute("DELETE FROM child_chunks")

    # 3. Change vector column to 1536d (handles any prior dimension: 1024 or 2560).
    op.execute(
        "ALTER TABLE child_chunks "
        "ALTER COLUMN embedding TYPE vector(1536)"
    )

    # 4. Recreate HNSW index — 1536d is within pgvector's 2000d hard limit.
    op.execute(
        "CREATE INDEX ix_child_chunks_embedding_hnsw "
        "ON child_chunks "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )


def downgrade() -> None:
    # Drop new index
    op.drop_index("ix_child_chunks_embedding_hnsw", table_name="child_chunks")

    # Clear rows (downgrade also invalidates embeddings)
    op.execute("DELETE FROM child_chunks")

    # Revert to 1024d
    op.execute(
        "ALTER TABLE child_chunks "
        "ALTER COLUMN embedding TYPE vector(1024)"
    )

    # Recreate old HNSW index (1024d is within the 2000d limit)
    op.execute(
        "CREATE INDEX ix_child_chunks_embedding_hnsw "
        "ON child_chunks "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
